import random
import discord
from discord.ext import commands

class Commands(commands.Cog):

    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def on_ready(self):
        print("Commands Cog has been loaded\n-----")

    @commands.command()
    async def fortune(self, ctx):
        """
        Opens a fortune cookie. deletes after 10 seconds
        """
        list = ["Someone is looking up to you, don't let them down.",
                "Run",
                "No snowflake in an avalanche ever feels responsible.",
                "Don't be afraid to take that big step.",
                "Ignore previous cookie",
                "I cannot help you, for i am just a cookie :smile:",
                "You will marry an athlete - if competitive eating can be considered a sport.",
                "You look pretty",
                "Ask not what your fortune cookie can do for you, but what can you do for the fortune cookie",
                "Enjoy yourself while you can.",
                "I see money in your future... It is not yours though.",
                "Death.",
                "This cookie is never gonna give you up, never gonna let you down.",
                "When you squeeze an orange, orange juice comes out - becuase that's what's inside",
                "If you think nobody cares if you are alive, try missing a couple car payments.",
                "Why not treat yourself to a good time instead of waiting for someone else to do it.",
                "Catch on fire with enthusiasm and people will come for miles to watch you burn.",
                "Love is on the horizon. The stars predict he will be tall, dark and a centaur.",
                "You laugh now, wait till you get home.",
                "Your pet is planning to eat you.",
                "Pigeon poop burns the retina for 13 hours. You will learn this the hard way.",
                "You are about to finish reading a fortune cookie.",
                "A good way to keep healthy is to eat more chinese food.",
                "Your resemblance to a muppet will prevent the world from taking you seriously.",
                "There is no angry way to say bubbles.",
                "The smart thing is to prepare for the unexpected.",
                "Life is a series of choices. Today yours are good ones.",
                "You will soon discover your hidden talent.",
                "Comfort zones are most often expanded through discomfort.",
                "What's the speed of dark?",
                "Only listen to fortune cookie, disregard all other fortune telling units",
                "Pull your head out your ass... Life won't be so shitty",
                "Your fortune said you need to make a donation. Give it to the admin",
                "Be cautious while walking in the darkness alone",
                "You will read this and say 'Geez! I could come up with better fortunes than that!'",
                "Tomorrow morning, Take a left as soon as you leave your home.",
                "You are one in a million.",
                "You should enhance your feminine side at this time.",
                "An interesting medical opportunity is in your new future.",
                "A real patriot is the fellow who get a parking ticket and rejoices that the system works.",
                "Pregnancy is a gift. And in your case it will also be a surprise.",
                "Something wonderful is about to happy.",
                "Learn chinese - Disease, 疾病(JiBing)",
                "Plan to be spontaneous tomorrow.",
                "It could be better, but it's good enough",
                "We don't know the future, but you got a free cookie.",
                "Family relationships will improve with time in bed.",
                "Work on improving your exercise routine",
                "Pick another fortune cookie.",
                "Ask your mum.",
                "She likes to flirt, but towards you her intentions are honorable.",
                "If a turtle doesn't have a shell, is it naked or homeless?",
                "Your wisdom makes you superior to others.",
                "The program 'fortune' is currently not installed. You can install it by typing: sudo apt-get install fortune-mod.",
                "Three can keep a secret, if you can get rid of two.",
                "Blessed are the children for they shall inherit the national debt.",
                "Harry, will you marry me?",
                "It's time to write a letter or email to one who is distant",
                "You will soon be receiving an important email.",
                "You will be rewarded for being a good listener.",
                "Don't panic.",
                "Never do anything halfway",
                "Do it now! Today will be yesterday tomorrow.",
                "Your problem just got bigger. Think, what have you done.",
                "You are the crispy noodle in the vegetarian salad of life.",
                "A closed mouth gathers no feet.",
                "The fortune you seek is in another cookie.",
                "A conclusion is simply the place where you got tired of thinking.",
                "A foolish man listens to his heart. A wise man listens to cookies.",
                "You will die alone and poorly dressed.",
                "A fanatic is one who can't change his mind, and won't change the subject.",
                "If you look back, you'll soon be going that way.",
                "An alien of some sort will be appearing to you shortly.",
                "Do not mistake temptation for opportunity.",
                "Flattery will go far tonight.",
                "He who laughs at himself never runs out of things to laugh at.",
                "He who laughs last is laughing at you.",
                "He who throws dirt is losing ground.",
                "Some men dream of fortunes, others dream of cookies.",
                "The greatest danger could be your stupidity.",
                "The world may be your oyster, but it doesn't mean you'll get its pearl.",
                "You will be hungry again in one hour.",
                "The road to riches is paved with homework.",
                "You can always find happiness at work on Friday.",
                "Actions speak louder than fortune cookies.",
                "Because of your melodic nature, the moonlight never misses an appointment.",
                "Don't behave with cold manners.",
                "Don't forget you are always on our minds.",
                "Fortune not found? Abort, Retry, Ignore.",
                "Never forget a friend. Especially if he owes you.",
                "Never wear your best pants when you go to fight for freedom.",
                "It is a good day to have a good day.",
                "All fortunes are wrong except this one.",
                "Someone will invite you to a Karaoke party.",
                "There is no mistake so great as that of being always right.",
                "You love Chinese food.",
                "I am worth a fortune.",
                "Some fortune cookies contain no fortune.",
                "Don't let statistics do a number on you.",
                "You are not illiterate.",
                "May you someday be carbon neutral.",
                "Avoid taking unnecessary gambles. Lucky numbers: 12, 15, 23, 28, 37",
                "Hard work pays off in the future. Laziness pays off now.",
                "You think it's a secret, but they know.",
                "Change is inevitable, except for vending machines.",
                "Shame on you for thinking a cookie is psychic.",
                "You will probably die of a heart attack or something",
                "Your wildest dreams will come true, assuming those dreams are about the extinction of honeybees.",
                "You are perfect just the way you are. Maybe a nose job.",
                "It's too late to stop climate change."
                "Throw a virgin into a volcano."
                "May you grow rich.",
                "God is dead, Santa Claus isn't real, and Snape kills dumbledoor",
                "Why are we still here?.. Just to suffer?.."
                "Mommy and Daddy love you very much. But apparently Mommy loves this groovy new thing called LSD more than she loves daddy."
                "Could i get some directions? ('To where?') To your heart.",
                "Wouldn't it be ironic to die in the living room?",
                "Come back later.. I am sleeping.('Yes, cookies need their sleep too')",
                "Jacking off has ruined my life - Mike",
                "Next time order the shrimp.",
                "What's that in your eye? Oh.. it's a sparkle.",
                "There's no such thing as an ordinary cat",
                "Why can dogs float in water?.. Because they're good buoys",
                "You couldn't be less interesting. But you're going to keep trying, aren't you.",
                "...",
                "You can totally do this!",
                "What ever is on your mind, just do it.",
                "Impossible is for the unwilling",
                "Take the risk, or lose the chance.",
                "A beautiful, smart, and loving person will be coming into your life.",
                "A faithful friend is a strong defense.",
                "A fresh start will put you on your way.",
                "A friend asks only for your time not your money.",
                "A friend is a present you give yourself.",
                "A gambler not only will lose what he has, but also will lose what he doesnt have.",
                "A golden egg of opportunity falls into your lap this month.",
                "A good friendship is often more important than a passionate romance.",
                "A good time to finish up old tasks.",
                "He who never sleeps is watching you.",
                "A hunch is creativity trying to tell you something.",
                "A lifetime friend shall soon be made.",
                "A lifetime of happiness lies ahead of you.",
                "Adventure can be real happiness.",
                "A soft voice may be awfully persuasive.",
                "A smile is your personal welcome mat.",
                "Advice, when most needed, is least heeded.",
                "All the troubles you have will pass away very quickly.",
                "All your hard work will soon pay off.",
                "Big Chungus",
                "An important person will offer you support.",
                "An inch of time is an inch of gold.",
                "Be careful or you could fall for some tricks today.",
                "It's Payday fellas.",
                "Because you demand more from yourself, others respect you deeply.",
                "Believe in yourself and others will too.",
                "Believe it can be done.",
                "Better ask twice than lose yourself once.",
                "Curiosity kills boredom. Nothing can kill curiosity.",
                "Dedicate yourself with a calm mind to the task at hand.",
                "Determination is what you need now.",
                "Do not be intimidated by the eloquence of others.",
                "Do not let ambitions overshadow small success.",
                "Do not demand for someone’s soul if you already got their heart.",
                "Do not make extra work for yourself.",
                "I'm getting the word...... Nonce.",
                "Do not underestimate yourself. Human beings have unlimited potentials.",
                "Don’t be discouraged, because every wrong attempt discarded is another step forward.",
                "Don’t just think, act!",
                "Don’t just spend time. Invest it.",
                "Don’t confuse recklessness with confidence.",
                "Don’t let the past and useless detail choke your existence.",
                "Don’t let friends impose on you, work calmly and silently.",
                "Don’t worry; prosperity will knock on your door soon.",
                "Every flower blooms in its own sweet time.",
                "Everyday in your life is a special occasion.",
                "Every wise man started out by asking many questions.",
                "Failure is the chance to do better next time.",
                "Fear and desire – two sides of the same coin",
                "Feeding a cow with roses does not get extra appreciation.",
                "Follow the middle path. Neither extreme will make you happy.",
                "For hate is never conquered by hate. Hate is conquered by love.",
                "Get your mind set…confidence will lead you on.",
                "Go for the gold today! You’ll be the champion of whatever.",
                "Go take a rest; you deserve it.",
                "You are nothing. Talentless. You shouldn't have been born.",
                "Good to begin well, better to end well",
                "Have a beautiful day.",
                "You are eating right now.",
                "You are currently using your PC",
                "If you continually give, you will continually have.",
                "I'm really feeling it.",
                "Dresses give no defense",
                "If your desires are not extravagant, they will be granted.",
                "In the end all things will be known.",
                "New ideas could be profitable.",
                "You should sell your feet pics.",
                "Perhaps you’ve been focusing too much on saving.",
                "People find it difficult to resist your persuasive manner.",
                "Practice makes perfect."
                "Po Says: Pandas like eating bamboo, but I prefer mine dipped in chocolate.",
                "Perhaps you should watch - https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                "Savor your freedom – it is precious.",
                "There is not much time left",
                "The night life is for you.",
                "The weather is wonderful.",
                "There is no mistake so great as that of being always right.",
                "Things don’t just happen; they happen just.",
                "Welcome change.",
                "Zebras",
                "You are busy, but you are happy.",
                "There are no accidents - Master Oogway",
                "You can keep a secret.",
                "You can see a lot just by looking.",
                "You can’t steal second base and keep your foot on first.",
                "You have a deep interest in all that is artistic.",
                "You have a deep appreciation of the arts and music.",
                "You have a yearning for perfection.",
                "You have an active mind and a keen imagination.",
                "You love challenge.",
                "You will enjoy good health.",
                "Your ability is appreciated.",
                "You are overrated",
                "Someone has lost trust in you."]
        item = random.choice(list)
        delete = ctx.message.delete()
        await delete
        await ctx.send(item, delete_after=10)

def setup(bot):
    bot.add_cog(Commands(bot))